version: 2

build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "18"
  commands:
    - npm install -g npm@latest
    - npm install
    - npm run build
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp dist/readthedocs-client.js $READTHEDOCS_OUTPUT/html
    - cp -r public/* $READTHEDOCS_OUTPUT/html
    - cp public/_/readthedocs-config.json $READTHEDOCS_OUTPUT/html
    # Inject our Javascript file :)
    - sed -i 's/<\/head>/<script src="readthedocs-client.js"><\/script><\/head>/g' $READTHEDOCS_OUTPUT/**/*.html
