version: 2.1

commands:
  run-tests:
    description: "Run test suite"
    steps:
      - checkout
      - run: npm ci
      - run: npm run test
  run-checks:
    description: "Run basic checks"
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  run-build:
    description: "Ensure assets compile properly"
    steps:
      - checkout
      - run: npm ci
      - run: npm run build

jobs:
  checks:
    docker:
      - image: "cimg/node:18.15.0"
    steps:
      - run-checks: {}
  test:
    docker:
      - image: "cimg/node:18.15.0"
    steps:
      - run-tests: {}
  build:
    docker:
      - image: "cimg/node:18.15.0"
    steps:
      - run-build: {}

workflows:
  version: 2
  build:
    jobs:
      - checks
      - test
      - build
